### ISSUE TITLE
ApplyLayer exit status 1 stdout

### ISSUE THREAD

**Issue by UboCA** [rnakato/ShortCake#8]
Hi, 
Thanks for developing this docker image and bring convenience for us.

I tried to pull the latest image and got the followed issue:

```
sudo docker pull rnakato/singlecell_jupyter

failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /root/.cpanm/work/1660378674.16440/Class-Accessor-Lite-0.08: invalid argument
```
I searched this error but have no idea. Could you give me anything help about it.

Best,
UboCA

**System**: Linux shpc-287-instance-DZ3jN8ek 5.4.0-147-generic #164-Ubuntu SMP Tue Mar 21 14:23:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
**Docker**: Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2

**Comment by eijynagai** [comment]
Hi UboCA,

Thanks for using our images!
It seems you're having some issues to write in your system. Have you encountered similar issues when pulling other images? 
We have changed the image name for the most updated versions. Would you please try to pull this one and let us know the output?

```
docker pull rnakato/shortcake
```

**Comment by UboCA** [comment]
> Hi UboCA,
> 
> Thanks for using our images! It seems you're having some issues to write in your system. Have you encountered similar issues when pulling other images? We have changed the image name for the most updated versions. Would you please try to pull this one and let us know the output?
> 
> ```
> docker pull rnakato/shortcake
> ```
> 
> Regards,
> 
> Eijy

Hi Eijy,

I also tried an image with less volume and it was OK. 
![image](https://user-images.githubusercontent.com/69028068/235563520-b8d9601a-d70f-498f-af02-937248e5c698.png)
This problem also occurred while I tried the latest image **shortcake**.

So what can I do in your advice, please let me know if anything is required about settings.

Best,
UboCA

**Comment by eijynagai** [comment]
Hi UboCA,

Sorry for the delayed reply.
I tested on an independent computer and couldn't replicate the issue. 
Searching about this issue seems to be a recent issue with new images and old docker. Could you please try the following steps:

1. Update Docker to the latest version if it's not.

2. Clear your Docker cache and free some space:
`sudo docker system prune -a`

3. Try pulling the image again:
`sudo docker pull rnakato/shortcake`

Please let me know if it works for you.

Eijy

**Comment by UboCA** [comment]
Hi,  @Eijy

Thanks for your advice.

I am using docker v20.10.21 (platformA).
After clearing cache by given command `sudo docker system prune -a`, the error still occurred.

I also tried to use `docker save` to export image as tar file in platform B (docker v20.10.21), and transfer the saved image to the platform A. However, using 'docker load < shortcake.tar' still leads to the same error:
`ApplyLayer exit status 1 stdout:  stderr: lchown /root/.cpanm/work/1660378674.16440/Class-Accessor-Lite-0.08: invalid argument`

Best, 
Xiangyang.

**Comment by rnakato** [comment]
Hi UboCA,
I cannot reproduce your error but I've made a new version `1.4.1` in which I removed `/root/.cpanm/work/*`. Could you try it?

**Comment by UboCA** [comment]
I searched the error 'failed to register layer: ApplyLayer exit status 1 stdout' and got [a simliar condition.](https://github.com/moby/moby/issues/43576)

![image](https://github.com/rnakato/ShortCake/assets/69028068/d47653a9-5e40-41ef-8b1b-c79b19d2ff95)

Hope that helps.

**Comment by rnakato** [comment]
That is strange because ShortCake v1.4.1 does not contain a folder in `/root/.cpanm/work/`.
If some docker caches cause this error, this problem might be solved by deleting `/root/.cpanm/work/` from the base image and building ShortCake in vanilla, but this will take a long time.
I'll note here when the build is complete.

**Comment by rnakato** [comment]
Hi UboCA,
I've made ShortCake v1.4.2 those base image does not contain `/root/.cpanm/work/`. Could you try it?

**Comment by UboCA** [comment]
> Hi UboCA, I've made ShortCake v1.4.2 those base image does not contain `/root/.cpanm/work/`. Could you try it?

@rnakato  Thanks , sure,  I will try it and note how it goes.

**Comment by UboCA** [comment]
@eijynagai @rnakato
Thanks for your reconstruction of this image and 1.4.2 is OK now.
![image](https://github.com/rnakato/ShortCake/assets/69028068/e368aca7-cc78-4423-976c-3b227266fced)
